services:
  frontend:
    networks:
      - customer-network
    image: node:20-slim
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- -p 3000 -H 0.0.0.0"
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    networks:
      - customer-network
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PYTHONPATH=/app
    depends_on:
      - frontend

  vscode:
    networks:
      - customer-network
    image: codercom/code-server:latest
    environment:
      - PASSWORD=eduadmin
    volumes:
      - .:/home/coder/project

networks:
  customer-network:
    driver: bridge
